@startuml
Clan "1" -- "*" pledgeallegiance
player "1" -- "*" sender
player "1" -- "*" player
servicetype "1" -- "*" servicetype
gameworldtype "1" -- "*" instanceupgrade
player "1" -- "*" author
subfamilyobject "1" -- "*" id_1
talenttype "1" -- "*" talentypecode
affinity "1" -- "*" affinitycode
featfamily "1" -- "*" family
gameworldtype "1" -- "*" instancetype
soul "1" -- "*" proprietaryentity
Clan "1" -- "*" proprietaryclan
tribe "1" -- "*" proprietarytribe
levelseeinvisible "1" -- "*" levelseeinvisible
family "1" -- "*" familly
buildingtype "1" -- "*" buildupgrade
familybuilding "1" -- "*" family
soul "1" -- "*" souls
cockroachtype "1" -- "*" cockroachtype
recipe "1" -- "*" recipe
subfamilyobject "1" -- "*" subfamily
areatype "1" -- "*" areatype
objecttype "1" -- "*" objecttype
gameworld "1" -- "*" target
gameworld "1" -- "*" actor
gameworld "1" -- "*" instance
approval "1" -- "*" id_1
soul "1" -- "*" soul
talent "1" -- "*" talent
objecttype "1" -- "*" objecttype
specie "1" -- "*" specie
objecttype "1" -- "*" plant
month_ "1" -- "*" month_
zodiac "1" -- "*" zodiac
profession "1" -- "*" profession
service "1" -- "*" service
diets "1" -- "*" diets
talentinventory "1" -- "*" talentinventory
day_ "1" -- "*" birthday
gameworld "1" -- "*" locationinstance
entity "1" -- "*" master
pack "1" -- "*" pack
entity "1" -- "*" customer
entity "1" -- "*" god
quest "1" -- "*" quest
entity "1" -- "*" entity
resourcenodetype "1" -- "*" resourcenodetype
entity "1" -- "*" targetentity
object "1" -- "*" targetobject
entity "1" -- "*" actorentity
object "1" -- "*" actorobject
entity "1" -- "*" proprietaryentity
buildingtype "1" -- "*" buildingtype
religion "1" -- "*" religion
object "1" -- "*" object
gameworld "1" -- "*" den
Clan "1" -- "*" targetclan
Clan "1" -- "*" actorclan
objecttype "1" -- "*" rewardtype
entity "1" -- "*" pnj
entity "1" -- "*" applicant
entity "1" -- "*" ConfessionTargets
entity "1" -- "*" creator
entity "1" -- "*" vendor
object "1" -- "*" id
matter "1" -- "*" matter
etatdumarchepast "1" -- "*" id_1
enchantrequire "1" -- "*" id_1
entity "1" -- "*" proprietary
mail "1" -- "*" mail
alert "1" -- "*" alert
credential "1" -- "*" credential
prerequisited "1" -- "*" code
Clan "1" -- "*" clan
BM "1" -- "*" bonus
tribe "1" -- "*" tribe
affinity "1" -- "*" affinity
prerequisited "1" -- "*" prerequisited
feat "1" -- "*" feat
knows "1" -- "*" soul, talent
component "1" -- "*" component
enchant "1" -- "*" enchant
entity "1" -- "*" target
queststep "1" -- "*" queststep
reward "1" -- "*" reward
news "1" -- "*" news
distinctions "1" -- "*" distinctions
announcement "1" -- "*" id_1
@enduml
