@startuml action_gobelin_sequence_complements

actor Utilisateur
participant "Interface Web" as UI
participant "Gobland" as System

Utilisateur -> UI : Clique sur "Jouer"
UI -> System : Vérifie les identifiants
alt #FFCCCC Identifiants incorrects
    UI -> Utilisateur : Redirige vers la page de connexion
    return
end

System -> System : Vérifie si un gobelin est enregistré
alt #lightgreen Gobelin trouvé
    System -> UI : Affiche la liste des gobelins + lien pour créer un nouveau
else #FFCCCC Aucun gobelin
    UI -> Utilisateur : Redirige vers la création de gobelin
end

Utilisateur -> UI : Choisit un gobelin
UI -> System : Charge l'interface d'utilisation du gobelin
System -> UI : Affiche l'interface

Utilisateur -> UI : Clique sur "Choisir une action"
UI -> Utilisateur : Affiche le menu des actions disponibles

alt Action = Se déplacer

alt Action = "Prier"
    group Action Prier
        System -> System : Effectue une requête pour trouver tous les dieux et leurs prières
        System -> UI : affiche une liste regroupant les dieux et leurs prières associées
        Utilisateur -> UI : Choisit un dieu et une prière
        UI -> System : Envoie le choix
        System -> System : Teste la réussite de la prière
        alt #lightgreen Réussite
            System -> System : Applique le bonus
            System -> UI : Affiche le succès de la prière
        else #FFCCCC Échec
            System -> UI : Affiche l'échec de la prière
        end
    end group

else Action = "Se concentrer"
    group Action Se concentrer
        System -> UI : Affiche une interface de choix de concentration
        Utilisateur -> UI : Choisit un pourcentage
        UI -> System : Transmet le choix
        System -> System : Applique le bonus de précision
        System -> UI : Affiche la réussite
    end group

else Action = "Équiper une pièce d'équipement"
    group Action Équiper équipement
        System -> UI : Affiche les pièces d'équipement disponibles dans l'inventaire seulement si elles sont identifiées
        Utilisateur -> UI : Choisit une pièce d’équipement
        UI -> System : Transmet le choix
        System -> System : Vérifie la disponibilité de l'emplacement
        alt #lightgreen Équipement possible
            System -> System : Équipe l’objet
            System -> UI : Affiche confirmation
        else #FFCCCC Échec
            System -> UI : Affiche un message d’erreur
        end
    end group

else Action = "Trouver son chemin"
    group Action Trouver son chemin
        System -> System : Recherche les points d’intérêt les plus proches
        alt #lightgreen Point trouvé
            System -> System : Calcule la direction optimale
            System -> UI : Affiche la direction
        else #FFCCCC Aucun point trouvé
            System -> UI : Affiche "aucun chemin identifié"
        end
    end group
System -> System : Déduit les PA requis
System -> UI : Affiche la vue mise à jour
@enduml