@startuml sequency_gestion_priere

actor Utilisateur
participant "Interface Web" as UI
participant "Gobland" as System
database "Base de données" as DB

UI -> System : Charge l'interface d'utilisation du gobelin
System -> DB : Récupère les données du gobelin
System -> UI : Affiche l'interface

Utilisateur -> UI : Clique sur "Pouvoir Divin"
UI -> System : Demande d'accès
System -> DB : Vérification des droits d'accès
alt #lightgreen accès autorisé
    System -> UI : Affiche le menu des Pouvoirs Divins disponibles
else #FFCCCC accès non autorisé
    System -> UI : Affiche un message d'erreur
end

Utilisateur -> UI : Clique sur "Gestion des Prières"
UI -> Utilisateur : Affiche l'interface de gestion des prières

alt Création/Modification d'une prière
    alt Création d'une prière
        Utilisateur -> UI : Clique sur "Créer"
        UI -> Utilisateur : Affiche l'interface de création de la prière
        Utilisateur -> UI : Sélectionne l'effet, la durée, le coût d'utilisation et un message
        UI -> System : Transmet les paramètres de création de la prière
    else Modification d'une prière
        Utilisateur -> UI : Clique sur "Modifier"
        UI -> Utilisateur : Affiche l'interface de modification de la prière
        Utilisateur -> UI : Modifie le coût d'utilisation
        UI -> System : Transmet les nouveaux paramètres de la prière
    end
    System -> DB : Vérifie les paramètres et contraintes
    alt #lightgreen paramètres corrects
        System -> DB : Enregistre la prière
        System -> DB : Met à jour les coûts de revient et la piété du dieu
        System -> UI : Affiche un message de confirmation
    else #FFCCCC paramètres incorrects
        System -> UI : Affiche un message d'erreur
    end
else Suppression d'une prière
    Utilisateur -> UI : Clique sur "Supprimer"
    UI -> Utilisateur : Affiche un message de demande de confirmation
    Utilisateur -> UI : Clique sur "Oui"
    UI -> System : Envoie la requête de suppression
    System -> DB : Supprime la prière
    System -> UI : Affiche un message de confirmation de la suppression
end

@enduml
