@startuml droit_divin_gestion_prieres

start

repeat
:Le système affiche l'interface d'utilisation du gobelin;

:L'utilisateur clique sur "Pouvoir divin";

backward :Le système affiche un message d'erreur;
repeat while (Le système vérifie que le gobelin a bien les droits) is (interdit) not (autorisé)

:Le système affiche l'interface dédiée aux dieux;

:L'utilisateur clique sur "Gestion des prières";

    partition #lightYellow "Gestion des prières" {
        :Le système affiche la liste des prières;

        if (L'utilisateur choisit une action) then (Création d'une prière)

            repeat
            :Le système affiche l'interface de création d'une prière;
            :L'utilisateur sélectionne les effets, les coûts d'utilisation et écrit un message;
            backward :Le système affiche un message d'erreur;
            repeat while (Le système vérifie les paramètres de la prière.) is (incorrect) not (correct)

        elseif (Suppression d'une prière)
            :Le système supprime la prière;
            stop

        elseif (Modification d'une prière)

            repeat
            :Le système affiche l'interface de modification d'une prière;
            :L'utilisateur modifie le coût de la prière;
            backward :Le système affiche un message d'erreur;
            repeat while (Le système vérifie les paramètres de la prière.) is (incorrect) not (correct)

        endif
        
        :Le système met à jour la prière et détermine les coûts de revient ainsi que la perte de piété du dieu.;
        :Le système affiche la liste des prières mise à jour;
    }

stop

@enduml