@startuml action_gobelin2

start

:L'utilisateur clique sur "Jouer";

if (identifiants corrects ?) then (Oui)

else (Non)
    :Redirige vers la page de connexion;
    stop
endif

if (L'utilisateur a un gobelin enregistré) then (Oui)
    :Le système liste ses gobelins, avec la possibilité d’en créer un nouveau via un lien dédié;

else (Non)
    :Redirige vers la page de création de gobelin;
endif

:L'utilisateur choisit un gobelin;

:Le système affiche l'interface d'utilisation du gobelin;

:L'utilisateur clique sur "Choisir une action";

    
if (L'utilisateur clique sur l'action "Prier")
    partition #CCCCFF "Action Prier" {
    if (Le système vérifie que l'utilisateur a suffisamment de points d'action) then (Oui)
        :Le système affiche une liste regroupant les dieux et leurs prières associées;
        :L'utilisateur choisit un dieu et une prière associée;

        if (Test de réussite de la prière) then (Succès)
            :Le système retire des points de piété au dieu concerné;
            :Le système applique le bonus lié à la prière choisie;
            :Le système affiche un message indiquant le succès de la prière;
        else (Échec)
            :Le système donne des points de piété au dieu concerné;
            :Le système affiche un message d'échec de la prière;
        endif
    else (Non)
    endif
    }
    
elseif (L'utilisateur clique sur l'action "Se concentrer")
    partition #E0CCFF "Action Se concentrer" {
        :Le système affiche une interface pour choisir un pourcentage de concentration avec leurs coûts en PA;
        :L'utilisateur choisit un pourcentage;

        if (Le gobelin a suffisamment de PA) then (Oui)
            :Le système applique un bonus temporaire en précision;
            :Le système affiche un message confirmant la concentration réussie;
        else (Non)
            :Le système affiche un message indiquant un manque de PA;
        endif
    }
    
elseif (L'utilisateur clique sur l'action "Équiper une pièce d'équipement")
    partition #FFD580 "Action Équiper un équipement" {
        :Le système affiche les pièces d'équipement disponibles dans l'inventaire seulement si elles sont identifiées;
        :L'utilisateur sélectionne une pièce d'équipement;

        if (L'équipement est identifié et l'emplacement est libre) then (Oui)
            :Le système équipe l'objet sur le gobelin;
            :Le système affiche un message de confirmation;
        else (Non)
            :Le système affiche un message d'échec (objet non identifié ou emplacement occupé);
        endif
    }
    
elseif (L'utilisateur clique sur l'action "Trouver son chemin")
    partition #A0E7E5 "Action Trouver son chemin" {
        :Le système identifie les points d'intérêt de la zone (escaliers, entrées de donjon, etc.);
        :Le système calcule le point d'intérêt le plus proche du gobelin;

        if (Un point d'intérêt est trouvé) then (Oui)
            :Le système affiche la direction vers le point le plus proche;
        else (Non)
            :Le système affiche un message indiquant qu’aucune destination n’a été trouvée;
        endif
    }
endif

:Le système réduit les PA du gobelin selon le coût de l'action;
:Le système affiche la vue avec les données mises à jour du gobelin;
stop

@enduml