@startuml action_abaisser_defense

start

:Le système affiche l'interface d'utilisation du gobelin;

:L'utilisateur clique sur "Abaisser sa défense";

    partition #D0F0C0 "Action Abaisser sa défense" {
        :Le système affiche un message exigeant une confirmation;
        :L'utilisateur confirme;
        :Le système applique le malus pour abaisser les stats défensives du gobelin à 0;
    }

:Le système réduit les PA du gobelin selon le coût de l'action;
:Le système affiche la vue avec les données mises à jour du gobelin;
stop

@enduml
