@startuml action_gobelin

start

:L'utilisateur clique sur "Jouer";

if (identifiants corrects ?) then (Oui)

else (Non)
    :Redirige vers la page de connexion;
    stop
endif

if (L'utilisateur a un gobelin enregistré) then (Oui)
    :Le système liste ses gobelins, avec la possibilité d’en créer un nouveau via un lien dédié;

else (Non)
    :Redirige vers la page de création de gobelin;
endif

:L'utilisateur choisit un gobelin;

:Le système affiche l'interface d'utilisation du gobelin;

:L'utilisateur clique sur "Choisir une action";

if (Le système affiche un menu déroulant avec toutes les actions possibles du gobelin) then (L'utilisateur clique sur "Se déplacer")
    partition #lightGreen "Utilisation action basique" {
        :Le système affiche la vue dédiée au déplacement du gobelin;
        :L'utilisateur choisit de se déplacer à gauche (y-1);
        
        if (Le système vérifie qu'il n'y a pas d'obstacle) then (Déplacement possible)
            :Le système déplace le gobelin dans la direction souhaitée et met à jour les coordonnées de l'utilisateur;
        else (Déplacement impossible)
            :Le système ne déplace pas le gobelin dans la direction souhaitée;
        endif
    }
else (L'utilisateur clique sur la technique "Boule de feu")
    partition #FFCCCC "Utilisation technique" {
    if (Le système vérifie que l'utilisateur a suffisamment de points d'action) then (Oui)
        :Le système affiche la vue de ciblage d'une cible;
        :L'utilisateur sélectionne la cible via un menu listant toutes les cibles à portée;
        
        if (Test de la compétence) then (Oui)
            :Le système calcule les dégâts liés à la technique et aux statistiques du lanceur;
            :Le système applique les dégâts de la technique à la cible, en les réduisant selon ses statistiques défensives;
        else (Non)
            :Le système affiche un message indiquant que l'action a échoué;
        endif
        
    else (Non)
    endif
    }
endif

:Le système affiche la vue avec les données mises à jour du gobelin;
stop

@enduml
